title: Veritas
description: Creating communities around international students to help them and their families flourish.
email: info@veritased.org
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://veritased.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [ruby, Gemfile, Gemfile.lock]
